//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Y2020.Gr124.ADO.NET.SpecialTaskEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        public short componentNumber { get; set; }
        public string componentName { get; set; }
        public string componentNameRu { get; set; }
        public string componentFormula { get; set; }
        public decimal componentMolarWeignt { get; set; }
    }
}
