//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Y2020.Gr124.ADO.NET.SpecialTaskEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public string gasName { get; set; }
        public Nullable<short> gasSize { get; set; }
        public Nullable<decimal> gasDencity { get; set; }
        public Nullable<decimal> gasConstant { get; set; }
        public string gasPath { get; set; }
    }
}
