//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Y2020.Gr124.ADO.NET.Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public string elementName { get; set; }
        public decimal elementAtomicWeight { get; set; }
    }
}
