//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Y2020.Gr124.ADO.NET.Task
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GasEntities : DbContext
    {
        public GasEntities()
            : base("name=GasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
    
        public virtual int mixtureCalculation(string mixtureName)
        {
            var mixtureNameParameter = mixtureName != null ?
                new ObjectParameter("mixtureName", mixtureName) :
                new ObjectParameter("mixtureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mixtureCalculation", mixtureNameParameter);
        }
    }
}
