//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCalculationProgram4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GasEntities : DbContext
    {
        public GasEntities()
            : base("name=GasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<Gas> Gases { get; set; }
        public virtual DbSet<Mixture> Mixtures { get; set; }
    
        public virtual int mixtureCalculation(string mixtureName)
        {
            var mixtureNameParameter = mixtureName != null ?
                new ObjectParameter("mixtureName", mixtureName) :
                new ObjectParameter("mixtureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mixtureCalculation", mixtureNameParameter);
        }
    
        public virtual int mixtureCalculationOutput(string mixtureName, ObjectParameter mixtureDensity, ObjectParameter mixtureR)
        {
            var mixtureNameParameter = mixtureName != null ?
                new ObjectParameter("mixtureName", mixtureName) :
                new ObjectParameter("mixtureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mixtureCalculationOutput", mixtureNameParameter, mixtureDensity, mixtureR);
        }
    
        public virtual int OutputD(string mixtureName, ObjectParameter mixtureDensity)
        {
            var mixtureNameParameter = mixtureName != null ?
                new ObjectParameter("mixtureName", mixtureName) :
                new ObjectParameter("mixtureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OutputD", mixtureNameParameter, mixtureDensity);
        }
    
        public virtual int OutputR(string mixtureName, ObjectParameter mixtureR)
        {
            var mixtureNameParameter = mixtureName != null ?
                new ObjectParameter("mixtureName", mixtureName) :
                new ObjectParameter("mixtureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OutputR", mixtureNameParameter, mixtureR);
        }
    }
}
