//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCalculationProgram4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mixture
    {
        public string gasName { get; set; }
        public string componentName { get; set; }
        public Nullable<decimal> volume { get; set; }
        public string Component_componentName { get; set; }
        public string Gas_gasName { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Gas Gas { get; set; }
    }
}
