//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.Y2020.Gr124.ADO.NET.SpecialTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        public string compositionName { get; set; }
        public string componentFormula { get; set; }
        public decimal componentVolume { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
